### ISSUE TITLE
LogicVis Feedback

### ISSUE THREAD

**Issue by orenjina** [cagesellchen/TyrantVC#1]
Summary: 7/7 pts

Comments:
Great product! Was there a typo in your motivation? You said that Charcoal has a VC system but imply that it does not immediately after. Also, do you plan on doing anything in the case that there is no internet connection? On a side note, are you planning to cater your product towards your target audience in ways other than making it less technical (not that it needs to be)? These are just some small things to think about, and we look forward to seeing your software!

Rubric:
I understand the problem this group is trying to solve.
Yes - public version control system for Maya

I understand why current solutions are insufficient.
Yes - no such plugin exists

I understand this group's proposed approach.
Yes - a plugin that adds a UI section with connection to git

I understand how this team will evaluate their approach.
Yes - correctness testing + usability testing

This team included a schedule.
Yes

Every item on this team's schedule is measurable.
Yes - each week's goal is a concrete product

This team included appropriate citations to related work, including from the scientific literature.
Yes

**Comment by wilkc** [comment]
Typo fixed, and clarified about using Git locally rather than GitHub. Thanks for your feedback!
